### ISSUE TITLE
Lily Pad Stuttering

### ISSUE THREAD

**Issue by SafeOfArsenal** [MehVahdJukaar/betterlily-multi#1]
trying to place a block that you cant place on a lily pad will have it stutter (some block examples are dead bushes and #flowers)

**Comment by MehVahdJukaar** [comment]
That's just due to how the mod works. It lowers the pad for one tick and let's the player attempt to place stuff for maximum compatibility. I don't think I can change this easily and yea it's a bug technically but I kind of like the effect of the pad lowering a but when you interact with it, kind of like you are pushing it like a button

**Comment by MehVahdJukaar** [comment]
made it less visible
